### ISSUE TITLE
Beweis Tasche für Polizisten

### ISSUE THREAD

**Issue by ctillmann** [ctillmann/UntitledLife_mission#13]
Polizisten können eine Beweis Tasche kaufen, in die bspw. Waffen und Munition gelegt werden können.
Ein Tutorial gibt es [hier](https://native-network.net/thread/3452-tutorial-beweis-tasche-f%C3%BCr-polizisten/).

**Comment by Jonnynox** [comment]
Das möchte ich rein haben

**Comment by StMcCaffrey** [comment]
Keine schlecht idee grade auch für das FBI

**Comment by Crunchz** [comment]
Done
