### ISSUE TITLE
Speichern des Schadens und der Tankfüllung eines Fahrzeugs

### ISSUE THREAD

**Issue by ctillmann** [ctillmann/UntitledLife_mission#14]
Ein Tutorial gibt es [hier](https://native-network.net/thread/2207-tutorial-fahrzeug-schaden-und-tankf%C3%BCllung-speichern/).

**Comment by Jonnynox** [comment]
Hau rein

**Comment by StMcCaffrey** [comment]
Aufjedenfall

**Comment by Crunchz** [comment]
Done
