### ISSUE TITLE
Bank hacken

### ISSUE THREAD

**Issue by ctillmann** [ctillmann/UntitledLife_mission#15]
Dieser Skript ist für die 3.1.4.8, deswegen steht die Umsetzbarkeit aktuell noch im Raum.
Sonst gibt es [hier](https://native-network.net/thread/185-tutorial-hack-the-bank/) ein Tutorial.

**Comment by Jonnynox** [comment]
Das finde ich richtig nice das muss sein..

**Comment by Crunchz** [comment]
Done
