### ISSUE TITLE
AAN News Rundnachrichten

### ISSUE THREAD

**Issue by ctillmann** [ctillmann/UntitledLife_mission#19]
Könnte bspw. durch die Leitung der Polizei / des Rettungsdienstes verwendet werden, um über besondere Ereignisse zu berichten.
Ein Tutorial gibt es [hier](https://native-network.net/thread/2581-tutorial-altis-life-4-0-aan-news-rundnachrichten/).

**Comment by Jonnynox** [comment]
Jup bin ich dafür

**Comment by Crunchz** [comment]
Done
