### ISSUE TITLE
Cop / Medic Absperrungen

### ISSUE THREAD

**Issue by ctillmann** [ctillmann/UntitledLife_mission#5]
Ein Tutorial gibt es [hier](https://native-network.net/thread/3650-tutorial-altis-life-4-0-cop-medic-absperrungen-per-men%C3%BC/?postID=26840#post26840).

**Comment by StMcCaffrey** [comment]
Muss mit rein

**Comment by Jonnynox** [comment]
Das sehe ich auch so

**Comment by Crunchz** [comment]
Done
