### ISSUE TITLE
Fahrzeughändler mit 3D Ansicht

### ISSUE THREAD

**Issue by ctillmann** [ctillmann/UntitledLife_mission#6]
Ein Tutorial gibt es [hier](https://native-network.net/thread/3552-tutorial-flug-fahrzeug-h%C3%A4ndler-mit-3d-ansicht-und-eigenen-skins/?postID=26275#post26275).

**Comment by StMcCaffrey** [comment]
Kann man machen muss man aber nicht

**Comment by Jonnynox** [comment]
Ich würde es mir gerne mal anschauen

**Comment by Crunchz** [comment]
Done
