### ISSUE TITLE
Rundnachrichten für die Polizei

### ISSUE THREAD

**Issue by ctillmann** [ctillmann/UntitledLife_mission#7]
Ein Tutorial gibt es [hier](https://native-network.net/thread/1881-tutorial-4-0-rundnachrichten-f%C3%BCr-polizei/?pageNo=1).

**Comment by StMcCaffrey** [comment]
Muss unbedingt mit rein auch für die EMS

**Comment by Crunchz** [comment]
https://github.com/ctillmann/UntitledLife_mission/issues/19

Done
