### ISSUE TITLE
Admintool

### ISSUE THREAD

**Issue by ctillmann** [ctillmann/UntitledLife_mission#8]
Ein Tutorial gibt es [hier](https://native-network.net/thread/36-tutorial-admin-tool/?postID=26361#post26361).

Dieses Admintool muss in der Funktionalität und im Umfang angepasst werden.

* Angepasste Spawnpunkte
* Marktpreis reset entfernen
* Geld geben entfernen
* Eventuell Unsichtbarkeit?

**Comment by StMcCaffrey** [comment]
Würde ich aufjedenfall mit rein nehmen
zumindest unsichtbarkeit und porten
